# Generated by Django 3.1.4 on 2024-01-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
            ],
        ),
    ]
