# Generated by Django 3.1.4 on 2024-01-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_edge_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='label',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
