# Generated by Django 3.1.4 on 2024-01-10 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_node_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='traverse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='app.newtraverse'),
        ),
        migrations.AddField(
            model_name='node',
            name='traverse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='app.newtraverse'),
        ),
    ]
