# Generated by Django 3.1.4 on 2024-01-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_node_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='content',
            field=models.CharField(default=None, max_length=8000),
        ),
    ]
