# Generated by Django 3.1.4 on 2024-01-18 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_node_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=8000)),
                ('back', models.CharField(max_length=8000)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='app.node')),
            ],
        ),
    ]
