# Generated by Django 4.2.4 on 2023-08-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReciepeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=20)),
                ('r_description', models.TextField(max_length=500)),
                ('r_type', models.CharField(max_length=20)),
                ('r_created_at', models.DateField()),
                ('r_img', models.CharField(max_length=200)),
            ],
        ),
    ]
