# Generated by Django 4.2.4 on 2023-08-30 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReciepeTable',
            new_name='RecipeTable',
        ),
    ]
