# Generated by Django 3.0.5 on 2024-05-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_reciepetable_recipetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
