# Generated by Django 4.1.13 on 2025-01-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.EmailField(max_length=254)),
                ('cc_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
    ]
