# Generated by Django 4.1.13 on 2025-01-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='cc_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
